dist: trusty
sudo: false

language: python
python:
  - "3.6"

env:
  - SKIP_NETWORK_TESTS=0

install:
    - travis_retry pip install tox
script:
    - tox -e py36
after_success:
    - tox -e py36-coveralls
